.TH MONROUTE 1 monroute
.SH NAME
monroute \- Simple monitor to webcam routing utility for X.
.SH SYNOPSIS
.B monroute
.RB [ \-l ]
.RB [ \-m
.IR monitor]
.RB [ \-d
.IR device]
.RB [ \-r
.IR rate]
.SH DESCRIPTION
.B monroute
is a simple monitor to webcam routing utility for X.
.SH OPTIONS
.TP
.B \-l
lists available monitors
.TP
.BI \-m " monitor"
selects the monitor number to use.
.TP
.BI \-d " device"
selects the device number to use.
.TP
.BI \-r " rate"
sets the frame rate.
.TP
